## Exercise 10

Date: 11/16/2021 <br>
Group Name: Broken Toes <br>
Group Members: Emma Bright, Mike Santoro, Duncan Ferguson

***

In [1]:
import numpy as np
import math
import pandas as pd
from sklearn import tree
from sklearn.naive_bayes import *
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import *
from sklearn.inspection import permutation_importance
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN

### Part 1:  PCA

Principle Component Analysis (PCA) can be used to reduce the time needed to build machine learning models.  You are to apply PCA the weather prediction data set using GausianNP.
First create a table (or chart) of the explained_variance_ratio_ for the data set.  Then run your models for 1, 2, 3, 4, 5, 6, 7, 8, and all components.  Create a table (or chart) showing the accuracy as a function of the number of  components.

Create a function to perform the Gaussian NB machine learning algorithm.

In [2]:
def runGaussianNB(x_train, x_test, y_train, y_test):
	global gausianNB_predicted
	model = GaussianNB()
	model.fit(x_train,y_train)
	gausianNB_predicted = model.predict(x_test)
	accuracy = accuracy_score(y_test, gausianNB_predicted)
	imps = permutation_importance(model, x_test, y_test)

Read in the weather data.

In [3]:
df = pd.read_csv('cleanInfile.csv')
df.head()

,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2,13.4,22.9,0.6,13,44.0,13,14,20.0,24.0,71.0,22.0,1007.7,1007.1,8.000000,4.503167,16.9,21.8,0.0,0
1,2,7.4,25.1,0.0,14,44.0,6,15,4.0,22.0,44.0,25.0,1010.6,1007.8,4.437189,4.503167,17.2,24.3,0.0,0
2,2,12.9,25.7,0.0,15,46.0,13,15,19.0,26.0,38.0,30.0,1007.6,1008.7,4.437189,2.000000,21.0,23.2,0.0,0
3,2,9.2,28.0,0.0,4,24.0,9,0,11.0,9.0,45.0,16.0,1017.6,1012.8,4.437189,4.503167,18.1,26.5,0.0,0
4,2,17.5,32.3,1.0,13,41.0,1,7,7.0,20.0,82.0,33.0,1010.8,1006.0,7.000000,8.000000,17.8,29.7,0.0,0

Create a table of the Explained Variance Ratio for the dataset.

In [4]:

Y = df['RainTomorrow']
df2 = df.drop('RainTomorrow',axis=1)

x_train, x_test, y_train, y_test  = train_test_split( df2, Y,  test_size=0.20, random_state=1)
save_xtrain = x_train
save_xtest = x_test
save_ytrain = y_train
save_ytest = y_test
runGaussianNB(x_train, x_test, y_train, y_test)

pca = PCA()
x_train = pca.fit_transform(save_xtrain)
x_test = pca.fit_transform(save_xtest)
explained_variance = pca.explained_variance_ratio_
print("explained_variance = ")
print(explained_variance)

explained_variance =
[4.07654647e-01 1.69948241e-01 1.16531623e-01 8.23567947e-02
 6.58785819e-02 3.82306636e-02 3.27126462e-02 2.35252950e-02
 2.06964561e-02 1.71194122e-02 9.31231902e-03 5.77615443e-03
 3.77136678e-03 2.94156034e-03 1.18305227e-03 9.45496544e-04
 7.07025622e-04 6.47881113e-04 6.07843930e-05]

Run the Gaussian NB model for 1, 2, 3, 4, 5, 6, 7, 8, and all components.

In [5]:
accuracy_list= []
x_train = save_xtrain
x_test = save_xtest
# Run with all components
runGaussianNB(x_train, x_test, y_train, y_test)
accuracy_list.append(['all', accuracy_score(y_test, gausianNB_predicted)])


# Run with 1, 2, 3....., 8 components
for i in range (1, 9):
    pca = PCA(n_components=i)
    x_train = pca.fit_transform(save_xtrain)
    x_test = pca.fit_transform(save_xtest)
    runGaussianNB(x_train, x_test, y_train, y_test)
    accuracy_list.append( [str(i), accuracy_score(y_test, gausianNB_predicted)])

result = pd.DataFrame(accuracy_list, columns=["Number of Components", "Accuracy"])
result

  Number of Components  Accuracy
0                  all  0.812581
1                    1  0.798375
2                    2  0.824994
3                    3  0.825381
4                    4  0.830092
5                    5  0.829882
6                    6  0.817645
7                    7  0.813355
8                    8  0.810964

#### Based on this, how many components do you recommend using for constructing the GausianNB model for this data set?

Based on this output I would recommend using 4 components for the Gaussian Naive Bayes model as this has the highest level of accuracy.

***

### Part 2: Clustering Quality

Apply kmeans and dbmeans clustering to these labeled data sets - outfile1, outfile2, and outfile3. 
Calculate the following three metrics on the clustering for kmeans and dbscan:  homogeneity, completeness, and adjusted_mutual_info_score.

In [19]:
numClusters = 3

outfile = pd.read_csv('outfile.csv')
labels1 = pd.read_csv('outfile1.csv')
labels2 = pd.read_csv('outfile2.csv')
labels3 = pd.read_csv('outfile3.csv')

kmeans = KMeans(n_clusters=numClusters, random_state=0).fit(outfile)
db = DBSCAN(eps=1.5, min_samples=4).fit(outfile)

In [21]:
outfile['predKM'] = kmeans.labels_
outfile['predDB'] = db.labels_

In [22]:
outfile.head()

          a1         a2  predKM  predDB
0  18.900508  17.738116       0       0
1   9.355166  32.029783       2       1
2  20.111226  10.921999       0       0
3  30.752270  21.326611       1       2
4   9.816053  31.332579       2       1

In [28]:
labels1['actual'] = 0
labels2['actual'] = 1
labels3['actual'] = 2
labels = labels1.append(labels2, ignore_index = True)
labels = labels.append(labels3, ignore_index = True)
labels.head()

         a1         a2  actual
0  9.355166  32.029783       0
1  9.816053  31.332579       0
2  9.125756   4.129040       0
3  8.632544  36.134807       0
4  9.616329  27.776006       0

In [29]:
df = pd.merge(labels, outfile,  how='left', left_on=['a1','a2'], right_on = ['a1','a2'])
df

            a1         a2  actual  predKM  predDB
0     9.355166  32.029783       0       2       1
1     9.816053  31.332579       0       2       1
2     9.125756   4.129040       0       0       1
3     8.632544  36.134807       0       2       1
4     9.616329  27.776006       0       2       1
..         ...        ...     ...     ...     ...
995  29.860049  19.466960       2       1       2
996  28.471657   5.143157       2       0       2
997  30.043580  12.106201       2       0       2
998  28.667936  17.360923       2       0       2
999  30.433842  29.338134       2       1       2

[1000 rows x 5 columns]

In [32]:
print('K-Means')
print(f"Homogenity Score: {homogeneity_score(df.actual.to_list(),df.predKM.to_list())}")
print(f'Completeness Score: {completeness_score(df.actual.to_list(), df.predKM.to_list())}')
print(f'Adjusted Mutual Info Score: {adjusted_mutual_info_score(df.actual.to_list(), df.predKM.to_list())}')

K-Means
Homogenity Score: 0.3511815902654452
Completeness Score: 0.36120342674835665
Adjusted Mutual Info Score: 0.35492679063609317

In [34]:
print('DB Scan')
print(f"Homogenity Score: {homogeneity_score(df.actual.to_list(),df.predDB.to_list())}")
print(f'Completeness Score: {completeness_score(df.actual.to_list(), df.predDB.to_list())}')
print(f'Adjusted Mutual Info Score: {adjusted_mutual_info_score(df.actual.to_list(), df.predDB.to_list())}')

DB Scan
Homogenity Score: 1.0
Completeness Score: 0.99387940769096
Adjusted Mutual Info Score: 0.9969216318008042

#### A description of what these metrics tell you about the clustering?

Homogeneity Score is the measure that each cluster contains only members of a single class. <br>
The Completeness Score is a measure that all members of a given class are assigned to the same cluster. The two previous metrics can be combined to obtain the Adjusted Mutual Info Score since both are bounded below by 0.0 and above by 1.0 (higher is better).<br>
We can see from that excercise that DB-scan was much more effective at clustering this data-set as all of the scores for the metrics are much closer to 1 than those of K-Means.